// <auto-generated />
using System;
using BedrockSvrLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedrockSvrLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250830011819_AddedUserAvatarLinkToUserTable")]
    partial class AddedUserAvatarLinkToUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BedrockSvrLog.Data.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GameplayeDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpawnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.RealmEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("RealmEvent");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.User", b =>
                {
                    b.Property<string>("Xuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationDimension")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pfid")
                        .HasColumnType("TEXT");

                    b.HasKey("Xuid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.Login", b =>
                {
                    b.HasOne("BedrockSvrLog.Data.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.RealmEvent", b =>
                {
                    b.HasOne("BedrockSvrLog.Data.User", "User")
                        .WithMany("RealmEvents")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Data.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("RealmEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
