// <auto-generated />
using System;
using BedrockSvrLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedrockSvrLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902123208_removedUnusedCauseColumnInPlayerKillsTable")]
    partial class removedUnusedCauseColumnInPlayerKillsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BedrockSvrLog.Model.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GameplayeDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpawnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.PlayerDeaths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeathTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillerXuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KillerXuid");

                    b.HasIndex("Xuid");

                    b.ToTable("PlayerDeaths");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.RealmEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("RealmEvent");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.User", b =>
                {
                    b.Property<string>("Xuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationDimension")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pfid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnZ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Xuid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnZ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerKills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KillTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("PlayerKills");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.Login", b =>
                {
                    b.HasOne("BedrockSvrLog.Model.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Model.PlayerDeaths", b =>
                {
                    b.HasOne("BedrockSvrLog.Model.User", null)
                        .WithMany()
                        .HasForeignKey("KillerXuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BedrockSvrLog.Model.User", null)
                        .WithMany()
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BedrockSvrLog.Model.RealmEvent", b =>
                {
                    b.HasOne("BedrockSvrLog.Model.User", "User")
                        .WithMany("RealmEvents")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerKills", b =>
                {
                    b.HasOne("BedrockSvrLog.Model.User", null)
                        .WithMany()
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BedrockSvrLog.Model.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("RealmEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
