// <auto-generated />
using System;
using BedrockSvrLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedrockSvrLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BedrockSvrLog.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerDeathId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerKillsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerSpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSpawnZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerXuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RealmEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaperId");

                    b.HasIndex("PlayerDeathId");

                    b.HasIndex("PlayerKillsId");

                    b.HasIndex("PlayerXuid");

                    b.HasIndex("RealmEventId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GameplayeDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpawnTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paper");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerDeaths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeathTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KillerXuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("KillerXuid1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerXuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KillerXuid");

                    b.HasIndex("KillerXuid1");

                    b.HasIndex("PlayerXuid");

                    b.HasIndex("Xuid");

                    b.ToTable("PlayerDeaths");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerKills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KillTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerXuid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnPositionZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerXuid");

                    b.HasIndex("Xuid");

                    b.ToTable("PlayerKills");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.RealmEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Xuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Xuid");

                    b.ToTable("RealmEvent");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.User", b =>
                {
                    b.Property<string>("Xuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationDimension")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pfid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnZ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Xuid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpawnX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnY")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpawnZ")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("World");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.Article", b =>
                {
                    b.HasOne("BedrockSvrLog.Models.Paper", "Paper")
                        .WithMany("Articles")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BedrockSvrLog.Models.PlayerDeaths", "PlayerDeath")
                        .WithMany()
                        .HasForeignKey("PlayerDeathId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BedrockSvrLog.Models.PlayerKills", "PlayerKills")
                        .WithMany()
                        .HasForeignKey("PlayerKillsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BedrockSvrLog.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerXuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BedrockSvrLog.Models.RealmEvent", "RealmEvent")
                        .WithMany()
                        .HasForeignKey("RealmEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paper");

                    b.Navigation("PlayerDeath");

                    b.Navigation("PlayerKills");

                    b.Navigation("RealmEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.Login", b =>
                {
                    b.HasOne("BedrockSvrLog.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerDeaths", b =>
                {
                    b.HasOne("BedrockSvrLog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("KillerXuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BedrockSvrLog.Models.User", "Killer")
                        .WithMany()
                        .HasForeignKey("KillerXuid1");

                    b.HasOne("BedrockSvrLog.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerXuid");

                    b.HasOne("BedrockSvrLog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Killer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.PlayerKills", b =>
                {
                    b.HasOne("BedrockSvrLog.Models.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerXuid");

                    b.HasOne("BedrockSvrLog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.RealmEvent", b =>
                {
                    b.HasOne("BedrockSvrLog.Models.User", "User")
                        .WithMany("RealmEvents")
                        .HasForeignKey("Xuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.Paper", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BedrockSvrLog.Models.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("RealmEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
