// <auto-generated />
using BedrockSvrLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedrockSvrLog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BedrockSvrLog.Data.User", b =>
                {
                    b.Property<string>("Xuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pfid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Xuid");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
